name: checklist_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^2.3.6+1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  go_router: ^4.3.0
  hive: ^2.2.3
  iconsax: ^0.0.8
  overlay_support: ^2.0.1
  flutter_riverpod: ^2.0.0-dev.9
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
